name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**/*
      - cake.cs
      - ScrcpyConfig.slnx

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Run a Cake C# file
        uses: cake-build/cake-action@v3
        with:
          file-path: cake.cs
          target: Build
