name: Publish

on:
  workflow_dispatch:
    # Manual trigger

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Run a Cake C# file
        uses: cake-build/cake-action@v3
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE_URL: ${{ secrets.NUGET_SOURCE_URL }}
        with:
          file-path: cake.cs
          target: PackAndPush
